name: 'WiNet Extractor'
description: 'Extracts data from WiNet devices and sends to Home Assistant over MQTT.'
version: '0.1.9'
stage: 'stable'
slug: 'winet-extractor'
url: 'https://github.com/NickStallman/home-assistant-repo/tree/main/winet-extractor'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
map:
  - config:rw
panel_icon: mdi:solar-power
auth_api: false
hassio_role: 'default'
hassio_api: false
homeassistant_api: false
startup: 'application'
init: false
services:
  - mqtt:need

options:
  winet_host: ''
  mqtt_url: ''
  winet_user: ''
  winet_pass: ''
  poll_interval: 10
  analytics: true

schema:
  winet_host: str
  mqtt_url: str
  mqtt_user: str?
  mqtt_password: password?
  winet_user: str?
  winet_pass: str?
  poll_interval: int(1,3600)
  analytics: bool
