name: 'WiNet Extractor'
description: 'Extracts data from WiNet devices and sends to Home Assistant over MQTT.'
version: '0.4.1'
stage: 'stable'
slug: 'winet-extractor'
url: 'https://github.com/NickStallman/home-assistant-repo/tree/main/winet-extractor'
arch:
  - aarch64
  - amd64
panel_icon: mdi:solar-power
auth_api: false
hassio_role: 'default'
hassio_api: false
homeassistant_api: false
startup: 'application'
init: false
services:
  - mqtt:need

options:
  winet_host: ''
  mqtt_url: ''
  mqtt_prefix: 'homeassistant'
  winet_user: ''
  winet_pass: ''
  poll_interval: 10
  analytics: true
  ssl: false
  site_totals: true
  additional_winets: []

schema:
  winet_host: str
  mqtt_url: str
  mqtt_prefix: str
  winet_user: str?
  winet_pass: password?
  poll_interval: int(1,3600)
  analytics: bool
  ssl: bool
  site_totals: bool?
  additional_winets:
    - host: str
      user: str?
      pass: password?
      ssl: bool?
